{% set data = load_setup_py_data() %}

package:
  name: pypsbuilder
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/ondrolexa/pypsbuilder.git
  git_rev: {{ 'v' + data.get('version') }}

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - psbuilder = pypsbuilder.psbuilder:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyqt
    - qt
    - sip
    - numpy
    - matplotlib
    - networkx

  run:
    - python
    - pyqt
    - qt
    - sip
    - numpy
    - matplotlib
    - networkx

test:
  # Python imports
  imports:
    - pypsbuilder

build:
  script: python setup.py install

about:
  home: https://github.com/ondrolexa/pypsbuilder
  license: GPL-3.0
  license_file: LICENSE
  summary: Simplistic THERMOCALC front-end for constructing PT pseudosections
  license_family: GPL
#  doc_url: https://pypsbuilder.readthedocs.org
  dev_url: https://github.com/ondrolexa/pypsbuilder

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
